Dev yaseen
Yaseen-al/SpotSwap pull request #2
Opened 2018-03-15 16:54 UTC by Yaseen-al

Added car makes to fireBase, AuthenticationService and DataBaseService.

2018-03-15 21:58 UTC, SaiKhal commented on SpotSwap/Models/EndUser.swift
> +struct EndUser: Codable {
Is there a better name for this object? We arent sure what an "EndUser" is.

2018-03-15 22:09 UTC, SaiKhal commented on SpotSwap/Services/FireBase Services/DataBase Service/DataBaseService+EndUsers.swift
> +    func addNewEndUser(endUser: EndUser, user: User, completion: ()->Void, errorHandler: (Error)->Void){
What is the difference between EndUser and User? Caroline would like you to be more descriptive.

2018-03-15 22:11 UTC, SaiKhal requested changes
Very nice but there is some ambuiguity with the Type "EndUser"

2018-03-16 17:20 UTC, caroline608 requested changes
Will close soy can commit new changes

2018-03-16 17:20 UTC, closed without merging